// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kubctmspfstabbhnnnnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1YmN0bXNwZnN0YWJiaG5ubm5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODQzMTYsImV4cCI6MjA2ODE2MDMxNn0.yRhuAAoy9Dsy2h4O5AXTkloN9eX-7Ama-w03psfIVM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});